import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">PhotosImportPhotos</Link>
        </li>
        <li>
          <Link to="/pricingandcalendaryesillimportunavailabledatesfromanotherwebsite">
            PricingandcalendarYesIllimportunavailabledatesfromanotherwebsite
          </Link>
        </li>
        <li>
          <Link to="/propertydetailslivingroomone">
            PropertyDetailsLivingRoomOne
          </Link>
        </li>
        <li>
          <Link to="/parkingpaidone">ParkingpaidOne</Link>
        </li>
        <li>
          <Link to="/propertysetupbreakfastdetailsyone">
            PropertySetupBreakfastDetailsyOne
          </Link>
        </li>
        <li>
          <Link to="/addproperty">Addproperty</Link>
        </li>
        <li>
          <Link to="/grouphomepage">Grouphomepage</Link>
        </li>
        <li>
          <Link to="/propertycategorypage">Propertycategorypage</Link>
        </li>
        <li>
          <Link to="/howmuchpropertytolist">Howmuchpropertytolist</Link>
        </li>
        <li>
          <Link to="/confirmation">Confirmation</Link>
        </li>
        <li>
          <Link to="/questionaboutproperty">Questionaboutproperty</Link>
        </li>
        <li>
          <Link to="/namelocation1stpageone">NameLocation1stPageOne</Link>
        </li>
        <li>
          <Link to="/namelocation2ndpageone">NameLocation2ndPageOne</Link>
        </li>
        <li>
          <Link to="/namelocation3rdpageone">NameLocation3rdPageOne</Link>
        </li>
        <li>
          <Link to="/propertysetuppropertydetails">
            PropertySetupPropertyDetails
          </Link>
        </li>
        <li>
          <Link to="/propertysetupamenitiesone">PropertySetupAmenitiesOne</Link>
        </li>
        <li>
          <Link to="/propertysetupbreakfastdetails">
            PropertySetupBreakfastDetails
          </Link>
        </li>
        <li>
          <Link to="/languageone">LanguageOne</Link>
        </li>
        <li>
          <Link to="/rulesone">RulesOne</Link>
        </li>
        <li>
          <Link to="/hostprofileone">HostprofileOne</Link>
        </li>
        <li>
          <Link to="/photosimportphotosone">PhotosImportPhotosOne</Link>
        </li>
        <li>
          <Link to="/photosimportphotosairbnbone">
            PhotosImportPhotosAirbnbOne
          </Link>
        </li>
        <li>
          <Link to="/pricingandcalendarnoone">PricingandcalendarNoOne</Link>
        </li>
        <li>
          <Link to="/pricingandcalendaryesone">PricingandcalendarYesOne</Link>
        </li>
        <li>
          <Link to="/pricingandcalendaryestwoone">
            PricingandcalendarYesTwoOne
          </Link>
        </li>
        <li>
          <Link to="/pricingandcalendarpricepernightone">
            PricingandcalendarPricepernightOne
          </Link>
        </li>
        <li>
          <Link to="/pricingandcalendarrateplansone">
            PricingandcalendarRateplansOne
          </Link>
        </li>
        <li>
          <Link to="/parkingone">ParkingOne</Link>
        </li>
        <li>
          <Link to="/pricingandcalendarfiveone">PricingandcalendarFiveOne</Link>
        </li>
        <li>
          <Link to="/pricingandcalendaryesillconnectwithachannelmanagerone">
            PricingandcalendarYesIllconnectwithachannelmanagerOne
          </Link>
        </li>
        <li>
          <Link to="/propertydetailsotherspaces">
            PropertyDetailsOtherSpaces
          </Link>
        </li>
        <li>
          <Link to="/propertysetupbreakfastdetailsnone">
            PropertySetupBreakfastDetailsnOne
          </Link>
        </li>
        <li>
          <Link to="/parkingfreeone">ParkingfreeOne</Link>
        </li>
        <li>
          <Link to="/propertydetailsbedroomtwo">PropertyDetailsBedroomTwo</Link>
        </li>
        <li>
          <Link to="/pricingandcalendarnoiwontsyncmyavailability">
            PricingandcalendarNoIwontsyncmyavailability
          </Link>
        </li>
        <li>
          <Link to="/namelocation1stpage">NameLocation1stPage</Link>
        </li>
        <li>
          <Link to="/namelocation2ndpage">NameLocation2ndPage</Link>
        </li>
        <li>
          <Link to="/namelocation3rdpage">NameLocation3rdPage</Link>
        </li>
        <li>
          <Link to="/propertysetuppropertydetailsone">
            PropertySetupPropertyDetailsOne
          </Link>
        </li>
        <li>
          <Link to="/propertydetailslivingroom">PropertyDetailsLivingRoom</Link>
        </li>
        <li>
          <Link to="/propertydetailsotherspacesone">
            PropertyDetailsOtherSpacesOne
          </Link>
        </li>
        <li>
          <Link to="/propertydetailsbedroomtwoone">
            PropertyDetailsBedroomTwoOne
          </Link>
        </li>
        <li>
          <Link to="/propertysetupamenities">PropertySetupAmenities</Link>
        </li>
        <li>
          <Link to="/propertysetupbreakfastdetailsone">
            PropertySetupBreakfastDetailsOne
          </Link>
        </li>
        <li>
          <Link to="/propertysetupbreakfastdetailsy">
            PropertySetupBreakfastDetailsy
          </Link>
        </li>
        <li>
          <Link to="/propertysetupbreakfastdetailsn">
            PropertySetupBreakfastDetailsn
          </Link>
        </li>
        <li>
          <Link to="/parking">Parking</Link>
        </li>
        <li>
          <Link to="/parkingpaid">Parkingpaid</Link>
        </li>
        <li>
          <Link to="/language">Language</Link>
        </li>
        <li>
          <Link to="/rules">Rules</Link>
        </li>
        <li>
          <Link to="/hostprofile">Hostprofile</Link>
        </li>
        <li>
          <Link to="/parkingfree">Parkingfree</Link>
        </li>
        <li>
          <Link to="/photosimportphotosairbnb">PhotosImportPhotosAirbnb</Link>
        </li>
        <li>
          <Link to="/pricingandcalendarno">PricingandcalendarNo</Link>
        </li>
        <li>
          <Link to="/pricingandcalendaryes">PricingandcalendarYes</Link>
        </li>
        <li>
          <Link to="/pricingandcalendaryestwo">PricingandcalendarYesTwo</Link>
        </li>
        <li>
          <Link to="/pricingandcalendarrateplans">
            PricingandcalendarRateplans
          </Link>
        </li>
        <li>
          <Link to="/pricingandcalendarfive">PricingandcalendarFive</Link>
        </li>
        <li>
          <Link to="/pricingandcalendaryesillconnectwithachannelmanager">
            PricingandcalendarYesIllconnectwithachannelmanager
          </Link>
        </li>
        <li>
          <Link to="/pricingandcalendarpricepernight">
            PricingandcalendarPricepernight
          </Link>
        </li>
        <li>
          <Link to="/pricingandcalendaryesillimportunavailabledatesfromanotherwebsiteone">
            PricingandcalendarYesIllimportunavailabledatesfromanotherwebsiteOne
          </Link>
        </li>
        <li>
          <Link to="/grouphomepageone">GrouphomepageOne</Link>
        </li>
        <li>
          <Link to="/addpropertyone">AddpropertyOne</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
